# Generated by Django 3.1.2 on 2020-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.TextField(max_length=100)),
                ('roll', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('facebook', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('about', models.TextField(max_length=100)),
            ],
        ),
    ]
